app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
// get, any, resource?? 이건http. 겟 포스트.. Method임. 뒤에 인자로
// 첫번째 인재로 들어가는것은 '/' 이건 resource
// 두번째 인자(function(){ return 'Hello World'}는 콜백.
Route::get('/', 'WelcomeController@index');

//Route::get('pages/aboutus','PageController@aboutus');
//Route::get('pages/location','PageController@location');
//Route::get('pages/copyright','PageController@copyright');
Route::get('/pages/{pageId}','PageController@page');
//Route::get('user/profile',['as'=>'profile',
//    'uses'=>'WelcomeController@profile']);
//Route::get('test',function(){
//
//    return route('profile');
//});
//Route::get('/',function(){
//    return 'Hello World!!!';
//});




//이걸 풀이하자면 사용자가 '/' URL로 접근하면 WelcomeController의 index 메소드를 실행하여 결과를 되돌려준다(@index)
//WelcomeController는 app/http/Controllers에 있음.
Route::resource('post', 'PostController');

/*
 * Named Route
 * 'as' 키워드를 사용하면 route에 이름을 지정 할 수 있다.
 * Route::get('user/profile',['as'=>'profile','uses' => 'UserController@showProfile']);
 * 이라우트는 profile이라는 이름을 지정해서 하겠다.
*/

app/Post.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model {

    public static $rules = [
        //앞으로 제목과 내용은 무조건 있어야함. 널 ㄴㄴ
//        'id' => 'required',  //id는 자동 inscreasement라 값을 입력하는게아니라 자동 데이터생성시 만들어짐. 여기다 이렇게 기술하면 에러남..
        'title' => 'required',
        'body' => 'required'
    ];

    // Don't forget to fill this array
    protected $fillable = ['title', 'body', 'thumbnail'];

}

app/Http/Controllers/PostController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;

use App\Post;
use Validator;
use Input;

class PostController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
    /**
     * public function index(){} post의 목록을 보여주는 역할을 수행 /post     -->GET
     * public function create(){} post의 작성하는 화면을 보여주는 역할을 수행  /post/create     -->GET
     * public function store(){} create()에서 작성한 내용을 실제 DB에 넣는 역할을 수행 /post   -->POST
     * public function show($id)(){} 목록에서 선택된 post를 출력하는 역할을 수행  /post/{postId}    -->GET
     * public function edit($id){} 목록에서 수정하기를 눌러 post를 수정하는 화면을 보여주는 역할을 수행  /post/{postId}/edit  -->GET
     * public function update($id){}  edit()에서 변경한 내용을 실제 DB에 update하는 역할 수행  /post/{postId}     -->PUTIPATCH
     * public function destroy($id){}  post를 삭제하는 역할 수행   /post/{postId}   -->DELETE
     */
	public function index()
	{
    //post컨트롤러의 index 메소드

        //페이지별로 가져옴. 5개씩..
        $posts = Post::orderBy('id', 'desc')->paginate(5);
        //모든 포스트 내용을 가져오기
//        $posts = Post::all();
        //뷰에 넘기기.
        return view('post.index', compact('posts'));

//        return '목록을 확인하는 화면 입니다.';

    }

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        return view('post.create');
//        return '생성을 위한 화면 입니다. ';
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
        $validator = Validator::make($data = Input::all(), Post::$rules);

        if ($validator->fails())
        {
            //리다이렉트 > 다시 이전페이지로 돌아가라. 이때 validate에서 보여준 에러 같이처리.
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        $post = new Post;
        if(Input::hasFile('thumbnail'))
        {
            $thumbnail = Input::file('thumbnail');

            $newFileName = time().'-'.$thumbnail->getClientOriginalName();
    //스토리지 패스
            $thumbnail->move(storage_path().'/files/', $newFileName);
            $post->thumbnail = $newFileName;
        }


        $post->title = Input::get('title');
        $post->body = Input::get('body');

        $post->save();


        return redirect()->route('post.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	    //id에 해당하는 post를 찾아서 post.show 뷰에 던져 출력
        $post = Post::findOrFail($id);

        return view('post.show', compact('post'));

//        return '내용을 볼 수 있는 화면입니다.';
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        $post = Post::find($id);
        return view('post.edit', compact('post'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
        $post = Post::findOrFail($id);

        $validator = Validator::make($data = Input::all(), Post::$rules);

        if ($validator->fails())
        {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $post->update($data);
        return redirect()->route('post.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
        Post::destroy($id);
        return redirect()->route('post.index');
	}
//	public function page($pageId){
//	    return view('layouts.page',[ 'pageName' => $pageId ]);
//    }

}

resources/views/post/create.blade.php
@extends('layouts.master')

@section('content')
<h2>글 생성하기</h2>
<form method="post" action="{{ route('post.index') }}" enctype="multipart/form-data">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <div class="form-group">
        <label name="title" for="title">제목</label>
        <input type="text" name="title" class="form-control" value=""/>
    </div>
    <div class="form-group">
        <label name="file" for="file">파일</label>
        <input type="file" name="thumbnail" value=""/>
    </div>
    <div class="form-group">
        <label name="body" for="body">내용</label>
        <textarea name="body" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <input type="submit" value="생성하기" class="btn btn-primary">
    </div>
</form>

@if($errors->any())
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        @foreach ($errors->all() as $message)
            {{ $message }}
        @endforeach
    </div>
@endif
@stop

resources/views/post/edit.blade.php
@extends('layouts.master')

@section('content')
    <h2>글 수정하기</h2>
    <form method="post" action="{{ route('post.update', $post->id) }}">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="_method" value="put">
        <div class="form-group">
            <label name="title" for="title">제목</label>
            <input type="text" name="title" class="form-control" value="{{ $post->title }}"/>
        </div>
        <div class="form-group">
            <label name="body" for="body">내용</label>
            <textarea name="body" class="form-control">{{ $post->body }}</textarea>
        </div>
        <div class="form-group">
            <input type="submit" value="수정하기" class="btn btn-primary">
        </div>
    </form>
@stop

resources/views/post/index.blade.php
@extends('layouts.master')
@section('content')
<h1>All Posts</h1>
  <ul class="list-group">
      <li class="list-group-item">

          <a>번호</a><a>제목</a>
      </li>
    @foreach($posts as $post)
      <li class="list-group-item">
          <a>{{$post->id}}</a>
          <a href="{{ route("post.show", $post->id) }}">{{ $post->title }}</a>

      </li>
    @endforeach
  </ul>

  {!! $posts->render() !!}

  <h3>
      <a href="{{ route('post.create') }}" class="btn btn-primary"> 글 작성하기 </a>
  </h3>
@stop

resources/views/post/show.blade.php
@extends('layouts.master')

@section('content')
    <h1>{{ $post->title }}</h1>

    <article>
        {{ $post->body }}
    </article>
    <article>
        {{ $post->thumbnail }}
    </article>

    <h3>
        <a href="{{ route('post.edit', $post->id) }}" class="btn btn-primary"> 글 수정하기 </a>
        <form method="post" action="{{ route('post.destroy', $post->id) }}">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="_method" value="delete">
            <button class="btn btn-primary" value=""/>글 삭제하기</button>

        </form>

        <a href="{{ route('post.index') }}" class="btn btn-primary"> 목록으로 </a>
    </h3>

@stop